name: smart-farming
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit>=1.28.0
      - tensorflow==2.15.0
      - numpy
      - pillow